title: "Mon Blog Minimaliste"
description: "Un blog simple et efficace."
author: "Votre Nom"
baseurl: "" # Gardez vide pour GitHub Pages
url: "https://votre-utilisateur.github.io/mon-blog" # Remplacez par votre URL GitHub Pages
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
